### ISSUE TITLE
[select] tips跟error报错时出现字体重复问题

### ISSUE THREAD

**Issue by suedar** [Tencent/tdesign-react#3079]
### tdesign-react 版本

1.5.1

### 期望结果

加个css就可以解决了
``` css
.t-is-error {
  .t-input__tips {
     display: none;
  } 
}

```

### 实际结果

<img width="571" alt="image" src="https://github.com/user-attachments/assets/eab8415c-c1b8-495f-8873-13409b42284f">
