### ISSUE TITLE
[全局样式] 全局样式 box-sizing 问题

### ISSUE THREAD

**Issue by moecasts** [Tencent/tdesign-react#806]
### 这个功能解决了什么问题

`tdesign` 的全局样式中将所有的元素都改成了`box-sizing: border-box;`，对于老项目来说很不友好，很多组件是基于 `content-box` 来写的，一引入样式就都乱了。
<img width="344" alt="wecom-temp-b3cd27c510b8e810b5c11e5d568bc92d" src="https://user-images.githubusercontent.com/37169906/170461179-da39fd53-4276-41eb-a5ae-395dee1815b6.png">

### 你建议的方案是什么

只改 `tdesign` 的组件的样式。
```css
[class^='t-'] {
  box-sizing: border-box;
}
```
